### PR TITLE
Fix provisioning of header missing in esp-idf 4.3.1

### PR DESCRIPTION
**Pull request by sirhcel**
Bulding the latest `rust-esp32-std-demo` (https://github.com/ivmarkov/rust-esp32-std-demo/commit/950d43896b7c37b8d1cba192b0a0d85870c5e103) currently fails due to `esp_vfs_usb_serial_jtag.h` missing in `esp-idf`:
```
$ cargo build --target riscv32imc-esp-espidf
    Updating crates.io index
   Compiling esp-idf-sys v0.30.4
error: failed to run custom build command for `esp-idf-sys v0.30.4`

Caused by:
 [...]
  PACKAGES:
   - framework-espidf 3.40301.0 (4.3.1)
   - tool-cmake 3.16.4
   - tool-esptoolpy 1.30100.210531 (3.1.0)
   - tool-ninja 1.9.0
   - toolchain-riscv32-esp 8.4.0+2021r1
   - toolchain-xtensa-esp32s2 8.4.0+2021r1
  Reading CMake configuration...
[...]
  /[...]/.cargo/registry/src/github.com-1ecc6299db9ec823/esp-idf-sys-0.30.4/src/include/esp-idf/bindings.h:40:10: fatal error: 'esp_vfs_usb_serial_jtag.h' file not found, err: true
  Error: Failed to generate bindings
```

It looks like `esp_vfs_usb_serial_jtag.h` gets provided by `esp-idf` starting with 4.4. This PR makes including this header conditional and groups the conditionally included VFS headers.

### CODE REVIEW

**Comment by ivmarkov** [comment]
I do not understand - is this specific for V4.3.1, or is V4.3.2 also affected? (V4.3.2 is the currently supported and latest V4.3.X version - also the default for `cargo build`.)

Because - nightly CI jobs happily compile esp-idf-sys & friends for V4.3.2 without any complaints?

**Comment by ivmarkov** [comment]
Heh. CI jobs happily compile for **esp32c3** where jtag is present. For esp32 and the other older chips, jtag will not be there.

**Comment by ivmarkov** [comment]
> Heh. CI jobs happily compile for **esp32c3** where jtag is present. For esp32 and the other older chips, jtag will not be there.

Hmm, just failed on me with esp32c3 too. Superstrange. Let's see... I just do not understand how CI jobs run fine...

**Comment by ivmarkov** [comment]
OK, so I was compiling with old PlatformIO which is still based on V4.3.1, which is no longer supported. Wiping out my `.embuild` folder so that it can recompile with newer PlatformIO / V4.3.2...

**Comment by sirhcel** [comment]
Sorry that I missed that the headers in question got added earlier.

Thank you! Works like a treat now. I just had to run `cargo clean` as well. So the following did the trick for me:
```
$ rm -r .embuild
$ cargo clean
$ cargo build --target riscv32imc-esp-espidf
```
