### ISSUE TITLE
"Cannot find value `MSG_DONTROUTE`" (and some others), upgrading to ESP-IDF 6.0.2

### ISSUE THREAD

**Issue by finalyards** [esp-rs/esp-idf-sys#421]
## Bug description

Some constants checked in `src/checks/libc.rs` do not seem to be available, when built with ESP-IDF 6.0.2.

In my project, there's a `raw` crate that uses `bindgen`. This builds, but when using the library in another crate I get the build errors, below.

The solution I took (locally) is to:

```
#[cfg(not(esp_idf_version_major = "6"))]
check_constants!(MSG_DONTROUTE);
```

Same for:

- `MSG_EOR`
- `SOMAXCONN`
- `IPV6_UNICAST_HOPS`
- `NI_MAXHOST`
- `NI_MAXSERV`
- `NI_NUMERICSERV`
- `NI_DGRAM`

I don't claim to know, what actually is going on here, nor how to fix this. Above does do as a work-around, but I don't feel comfortable sending a PR when not fully understanding the problem, or environment.

- Would you like to work on a fix? [y/n]

n

## To Reproduce

Unfortunately, my repo is private ATM.

I am using the `master` of `esp-idf-sys` as the basis (currently at commit `eaf69b2`). Otherwise, there are other hazards, working with ESP-IDF 6.0.x.

## Expected behavior

Ultimately, I can use ESP-IDF 6.0.x in my project.

## Environment

- Crate (`esp-idf-sys`) version: 

   ```
   # Needed for using with ESP-IDF 6.0 (breaks stuff with 5.5.4):
   [patch.crates-io]
   # https://github.com/esp-rs/embuild/issues/105
   embuild = { git = "https://github.com/esp-rs/embuild" }
   # > 0.46.2: https://github.com/esp-rs/esp-idf-hal/commit/95adcb9ad82288b20ef032e86e2dc9de824f45e3
   esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
   # > 0.52.1: https://github.com/esp-rs/esp-idf-svc/commit/e1761de00f0ac905da0ce592767184f8c851d5e0
   esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc" }
   # > 0.37.2: https://github.com/esp-rs/esp-idf-sys/commit/b0990892a63d808af25c7bda70f2726e76543743
   esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
   ```

- ESP-IDF branch or tag: `6.0.2`
- Target device (MCU): ESP32-C6
- OS: Ubuntu 26.04 LTS

**Comment by finalyards** [comment]
Oh, forgot: 

I'm using Newlib (not picolibc):

```
# 6.0.2 compatibility (EXPERIMENTAL!!!)
CONFIG_LIBC_NEWLIB=y
CONFIG_LIBC_NEWLIB_NANO_FORMAT=n
CONFIG_ESP_CONSOLE_UART=y
```

**Comment by finalyards** [comment]
This happens when targeting ESP-IDF 5.5.5 as well.

```
error[E0425]: cannot find value `MSG_DONTROUTE` in module `sys`
   --> /home/lima/.cargo/git/checkouts/esp-idf-sys-1f365e3f54debd76/8369f61/src/checks/libc.rs:108:18
    |
 12 |                 sys::$ident as i64 == libc::$ident as i64,
    |                      ------ due to this macro variable
...
108 | check_constants!(MSG_DONTROUTE);
    |                  ^^^^^^^^^^^^^
    |
   ::: /home/lima/target/riscv32imac-esp-espidf/release/build/esp-idf-sys-b4c15637b698b167/out/bindings.rs:3:237651
    |
  3 | ...st SO_ACCEPTCONN : u32 = 2 ; pub const SO_DONTROUTE : u32 = 16 ; pub const SO_USELOOPBACK : u32 = 64 ; pub const SO_LINGER : u32 = 128 ; pub const...
    |                                 ----------------------------------- similarly named constant `SO_DONTROUTE` defined here
    |
help: a constant with a similar name exists
    |
108 - check_constants!(MSG_DONTROUTE);
108 + check_constants!(SO_DONTROUTE);
    |
help: consider importing this constant
    |
  5 + use libc::MSG_DONTROUTE;
    |
```

<strike>Since the fix seems obvious, I'll try with a local patch. I will also make the repo public later today.</strike>

**Edit**

Quick PR that simply deactivates the conflicting checks is: https://github.com/esp-rs/esp-idf-sys/pull/426

**Comment by finalyards** [comment]
...as a generalization of this issue, I'd like to:

- know the current level of support for ESP-IDF 6.0.3

...so I will time my upgrade from 5.5.5 to 6.0.x meaningfully.

**Comment by ivmarkov** [comment]
> ...as a generalization of this issue, I'd like to:
> 
> * know the current level of support for ESP-IDF 6.0.3
> 
> ...so I will time my upgrade from 5.5.5 to 6.0.x meaningfully.

What you can safely use are versions of ESP-IDF **up to** the ones listed here: https://github.com/esp-rs/esp-idf-svc/blob/6292a2f9a041c6f1370c66678f360c164aef93a3/.github/workflows/ci.yml#L30

Up to 5 minutes ago, the listed max 5.5.x version was 5.5.3, and the listed 6.x version was 6.0

So no 5.5.5 support or 6.0.2 or 6.0.3.
I've now raised these to 5.5.5 and 6.0.3 to see what / if the build breaks, as per this issue, and fix that.

**Comment by ivmarkov** [comment]
@finalyards 

Turns out the reason why these constants can't be found is [because you are using a custom components list](https://github.com/finalyards-org/ezb-node/blob/b6ae778edc4bc67a72153c5915d136afa35f9679/.cargo/config.espidf.toml#L193).

... so when some of the components like LwIP are not compiled-in, their constants are not available in the generated bindings for ESP-IDF.

With that said, trimming the list of components for a project is perfectly fine, and the bug is indeed in `esp-idf-sys`. To be fixed shortly.

**Comment by ivmarkov** [comment]
Fixed by https://github.com/esp-rs/esp-idf-sys/commit/efb7e9402d7e4d5896c3dce41a68e93007ed23fe
